[package]
name = "mates-server"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.9"
mates-proto = { version = "0.1.0", path = "../proto" }
serde = { version = "1.0.229", features = ["derive"] }
tokio = { version = "1.53.2", features = ["macros", "rt-multi-thread", "net", "signal", "time"] }
tracing = "0.1.44"
tracing-subscriber = "0.3.23"
