//! What the daemon remembers between runs: this device's key (which is also its room's
//! identity and code), the rooms it has joined, and the friends allowed into its room.

use std::{fs, io, path::PathBuf};

use iroh::SecretKey;
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct Device {
    pub name: String,
    pub endpoint_id: String,
}

#[derive(Serialize, Deserialize, Default)]
struct State {
    /// Hex; regenerated by `reset_key`, which gives this device's room a new code.
    key: Option<String>,
    #[serde(default)]
    rooms: Vec<Device>,
    /// Devices the host has let into its room; they skip the approval prompt.
    #[serde(default)]
    friends: Vec<Device>,
}

pub struct Store {
    path: PathBuf,
    state: State,
}

fn dir() -> PathBuf {
    #[cfg(windows)]
    return PathBuf::from(
        std::env::var_os("ProgramData").unwrap_or_else(|| r"C:\ProgramData".into()),
    )
    .join("local mates");
    #[cfg(target_os = "macos")]
    return PathBuf::from("/Library/Application Support/local mates");
    #[cfg(all(unix, not(target_os = "macos")))]
    return PathBuf::from("/var/lib/local-mates");
}

impl Store {
    pub fn load() -> Self {
        let path = dir().join("state.json");
        let state = match fs::read(&path) {
            Ok(bytes) => serde_json::from_slice(&bytes).unwrap_or_else(|err| {
                tracing::warn!("ignoring unreadable {}: {err}", path.display());
                State::default()
            }),
            Err(_) => State::default(),
        };
        Self { path, state }
    }

    pub fn key(&mut self) -> io::Result<SecretKey> {
        if let Some(key) = self.state.key.as_ref().and_then(|k| k.parse().ok()) {
            return Ok(key);
        }
        self.reset_key()
    }

    pub fn reset_key(&mut self) -> io::Result<SecretKey> {
        let key = SecretKey::generate();
        self.state.key = Some(key.to_bytes().iter().map(|b| format!("{b:02x}")).collect());
        self.save()?;
        Ok(key)
    }

    pub fn rooms(&self) -> &[Device] {
        &self.state.rooms
    }

    pub fn friends(&self) -> &[Device] {
        &self.state.friends
    }

    /// Case-insensitive, since people type these.
    pub fn find_room(&self, name: &str) -> Option<&Device> {
        self.state.rooms.iter().find(|d| d.is_named(name))
    }

    pub fn is_friend(&self, endpoint_id: &str) -> bool {
        self.state
            .friends
            .iter()
            .any(|d| d.endpoint_id == endpoint_id)
    }

    pub fn remember_room(&mut self, room: Device) -> io::Result<()> {
        upsert(&mut self.state.rooms, room);
        self.save()
    }

    pub fn add_friend(&mut self, friend: Device) -> io::Result<()> {
        upsert(&mut self.state.friends, friend);
        self.save()
    }

    /// Removes saved rooms and friends with this name.
    pub fn forget(&mut self, name: &str) -> io::Result<bool> {
        let before = self.state.rooms.len() + self.state.friends.len();
        self.state.rooms.retain(|d| !d.is_named(name));
        self.state.friends.retain(|d| !d.is_named(name));
        let forgot = self.state.rooms.len() + self.state.friends.len() != before;
        if forgot {
            self.save()?;
        }
        Ok(forgot)
    }

    /// Write-then-rename so a crash never leaves a half-written file (and a lost room key).
    fn save(&self) -> io::Result<()> {
        fs::create_dir_all(dir())?;
        let tmp = self.path.with_extension("json.tmp");
        fs::write(&tmp, serde_json::to_vec_pretty(&self.state)?)?;
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            fs::set_permissions(&tmp, fs::Permissions::from_mode(0o600))?;
        }
        fs::rename(tmp, &self.path)
    }
}

impl Device {
    fn is_named(&self, name: &str) -> bool {
        self.name.eq_ignore_ascii_case(name.trim())
    }
}

/// Replaces any entry for the same device, so renames take effect and nothing duplicates.
fn upsert(list: &mut Vec<Device>, device: Device) {
    list.retain(|d| d.endpoint_id != device.endpoint_id);
    list.push(device);
}
