//! What the daemon remembers between runs: this device's key (which is also its room's
//! identity and code) and the rooms it has joined.

use std::{fs, io, path::PathBuf};

use iroh::SecretKey;
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct SavedRoom {
    pub name: String,
    pub endpoint_id: String,
}

#[derive(Serialize, Deserialize, Default)]
struct State {
    /// Hex; regenerated by `reset_key`, which gives this device's room a new code.
    key: Option<String>,
    #[serde(default)]
    rooms: Vec<SavedRoom>,
}

pub struct Store {
    path: PathBuf,
    state: State,
}

fn dir() -> PathBuf {
    #[cfg(windows)]
    return PathBuf::from(
        std::env::var_os("ProgramData").unwrap_or_else(|| r"C:\ProgramData".into()),
    )
    .join("local mates");
    #[cfg(target_os = "macos")]
    return PathBuf::from("/Library/Application Support/local mates");
    #[cfg(all(unix, not(target_os = "macos")))]
    return PathBuf::from("/var/lib/local-mates");
}

impl Store {
    pub fn load() -> Self {
        let path = dir().join("state.json");
        let state = match fs::read(&path) {
            Ok(bytes) => serde_json::from_slice(&bytes).unwrap_or_else(|err| {
                tracing::warn!("ignoring unreadable {}: {err}", path.display());
                State::default()
            }),
            Err(_) => State::default(),
        };
        Self { path, state }
    }

    pub fn key(&mut self) -> io::Result<SecretKey> {
        if let Some(key) = self.state.key.as_ref().and_then(|k| k.parse().ok()) {
            return Ok(key);
        }
        self.reset_key()
    }

    pub fn reset_key(&mut self) -> io::Result<SecretKey> {
        let key = SecretKey::generate();
        self.state.key = Some(key.to_bytes().iter().map(|b| format!("{b:02x}")).collect());
        self.save()?;
        Ok(key)
    }

    pub fn rooms(&self) -> &[SavedRoom] {
        &self.state.rooms
    }

    /// Case-insensitive, since people type these.
    pub fn find(&self, name: &str) -> Option<&SavedRoom> {
        self.state
            .rooms
            .iter()
            .find(|r| r.name.eq_ignore_ascii_case(name.trim()))
    }

    pub fn remember(&mut self, room: SavedRoom) -> io::Result<()> {
        self.state
            .rooms
            .retain(|r| r.endpoint_id != room.endpoint_id);
        self.state.rooms.push(room);
        self.save()
    }

    pub fn forget(&mut self, name: &str) -> io::Result<bool> {
        let before = self.state.rooms.len();
        self.state
            .rooms
            .retain(|r| !r.name.eq_ignore_ascii_case(name.trim()));
        let forgot = self.state.rooms.len() != before;
        if forgot {
            self.save()?;
        }
        Ok(forgot)
    }

    /// Write-then-rename so a crash never leaves a half-written file (and a lost room key).
    fn save(&self) -> io::Result<()> {
        fs::create_dir_all(dir())?;
        let tmp = self.path.with_extension("json.tmp");
        fs::write(&tmp, serde_json::to_vec_pretty(&self.state)?)?;
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            fs::set_permissions(&tmp, fs::Permissions::from_mode(0o600))?;
        }
        fs::rename(tmp, &self.path)
    }
}
